export const categories = [
  { id: 'affixes.awakened', text: 'Awakened', root: false },
  {
    id: 'affixes.beguiling',
    text: 'Beguiling',
    root: false,
  },
  {
    id: 'affixes.bolstering',
    text: 'Bolstering',
    root: false,
  },
  { id: 'affixes.bursting', text: 'Bursting', root: false },
  {
    id: 'affixes.explosive',
    text: 'Explosive',
    root: false,
  },
  { id: 'affixes.fortified', text: 'Fortified', root: false },
  {
    id: 'affixes.grievous',
    text: 'Grievous',
    root: false,
  },
  { id: 'affixes.infested', text: 'Infested', root: false },
  {
    id: 'affixes.inspiring',
    text: 'Inspiring',
    root: false,
  },
  { id: 'affixes.necrotic', text: 'Necrotic', root: false },
  {
    id: 'affixes.prideful',
    text: 'Prideful',
    root: false,
  },
  { id: 'affixes.quaking', text: 'Quaking', root: false },
  {
    id: 'affixes.raging',
    text: 'Raging',
    root: false,
  },
  { id: 'affixes.reaping', text: 'Reaping', root: false },
  {
    id: 'affixes.sanguine',
    text: 'Sanguine',
    root: false,
  },
  { id: 'affixes.skittish', text: 'Skittish', root: false },
  {
    id: 'affixes.spiteful',
    text: 'Spiteful',
    root: false,
  },
  { id: 'affixes.storming', text: 'Storming', root: false },
  {
    id: 'affixes.teeming',
    text: 'Teeming',
    root: false,
  },
  {
    id: 'affixes.tyrannical',
    text: 'Tyrannical',
    root: false,
  },
  {
    id: 'affixes.volcanic',
    text: 'Volcanic',
    root: false,
  },
  {
    id: 'class-roles.damage-dealing',
    text: 'Damage Dealing',
    root: false,
  },
  {
    id: 'class-roles.healing',
    text: 'Healing',
    root: false,
  },
  {
    id: 'class-roles.raid-leading',
    text: 'Raid Leading',
    root: false,
  },
  {
    id: 'class-roles.tanking',
    text: 'Tanking',
    root: false,
  },
  {
    id: 'class.death-knight',
    text: 'Death Knight',
    root: true,
  },
  {
    id: 'class.death-knight.blood',
    text: 'Blood Death Knight',
    root: false,
  },
  {
    id: 'class.death-knight.frost',
    text: 'Frost Death Knight',
    root: false,
  },
  {
    id: 'class.death-knight.unholy',
    text: 'Unholy Death Knight',
    root: false,
  },
  {
    id: 'class.demon-hunter',
    text: 'Demon Hunter',
    root: true,
  },
  {
    id: 'class.demon-hunter.havoc',
    text: 'Havoc Demon Hunter',
    root: false,
  },
  {
    id: 'class.demon-hunter.vengeance',
    text: 'Vengeance Demon Hunter',
    root: false,
  },
  { id: 'class.druid', text: 'Druid', root: true },
  {
    id: 'class.druid.balance',
    text: 'Balance Druid',
    root: false,
  },
  {
    id: 'class.druid.feral',
    text: 'Feral Druid',
    root: false,
  },
  {
    id: 'class.druid.guardian',
    text: 'Guardian Druid',
    root: false,
  },
  {
    id: 'class.druid.restoration',
    text: 'Restoration Druid',
    root: false,
  },
  { id: 'class.hunter', text: 'Hunter', root: true },
  {
    id: 'class.hunter.beast-mastery',
    text: 'Beast Mastery Hunter',
    root: false,
  },
  {
    id: 'class.hunter.marksmanship',
    text: 'Marksmanship Hunter',
    root: false,
  },
  {
    id: 'class.hunter.survival',
    text: 'Survival Hunter',
    root: false,
  },
  { id: 'class.mage', text: 'Mage', root: true },
  {
    id: 'class.mage.arcane',
    text: 'Arcane Mage',
    root: false,
  },
  { id: 'class.mage.fire', text: 'Fire Mage', root: false },
  {
    id: 'class.mage.frost',
    text: 'Frost Mage',
    root: false,
  },
  { id: 'class.monk', text: 'Monk', root: true },
  {
    id: 'class.monk.brewmaster',
    text: 'Brewmaster Monk',
    root: false,
  },
  {
    id: 'class.monk.mistweaver',
    text: 'Mistweaver Monk',
    root: false,
  },
  {
    id: 'class.monk.windwalker',
    text: 'Windwalker Monk',
    root: false,
  },
  { id: 'class.paladin', text: 'Paladin', root: true },
  {
    id: 'class.paladin.holy',
    text: 'Holy Paladin',
    root: false,
  },
  {
    id: 'class.paladin.protection',
    text: 'Protection Paladin',
    root: false,
  },
  {
    id: 'class.paladin.retribution',
    text: 'Retribution Paladin',
    root: false,
  },
  { id: 'class.priest', text: 'Priest', root: true },
  {
    id: 'class.priest.discipline',
    text: 'Discipline Priest',
    root: false,
  },
  {
    id: 'class.priest.holy',
    text: 'Holy Priest',
    root: false,
  },
  { id: 'class.priest.shadow', text: 'Shadow Priest', root: false },
  {
    id: 'class.rogue',
    text: 'Rogue',
    root: true,
  },
  {
    id: 'class.rogue.assassination',
    text: 'Assassination Rogue',
    root: false,
  },
  {
    id: 'class.rogue.combat',
    text: 'Combat Rogue',
    root: false,
  },
  {
    id: 'class.rogue.outlaw',
    text: 'Outlaw Rogue',
    root: false,
  },
  {
    id: 'class.rogue.subtlety',
    text: 'Subtlety Rogue',
    root: false,
  },
  { id: 'class.shaman', text: 'Shaman', root: true },
  {
    id: 'class.shaman.elemental',
    text: 'Elemental Shaman',
    root: false,
  },
  {
    id: 'class.shaman.enhancement',
    text: 'Enhancement Shaman',
    root: false,
  },
  {
    id: 'class.shaman.restoration',
    text: 'Restoration Shaman',
    root: false,
  },
  { id: 'class.warlock', text: 'Warlock', root: true },
  {
    id: 'class.warlock.affliction',
    text: 'Affliction Warlock',
    root: false,
  },
  {
    id: 'class.warlock.demonology',
    text: 'Demonology Warlock',
    root: false,
  },
  {
    id: 'class.warlock.destruction',
    text: 'Destruction Warlock',
    root: false,
  },
  { id: 'class.warrior', text: 'Warrior', root: true },
  {
    id: 'class.warrior.arms',
    text: 'Arms Warrior',
    root: false,
  },
  {
    id: 'class.warrior.fury',
    text: 'Fury Warrior',
    root: false,
  },
  {
    id: 'class.warrior.protection',
    text: 'Protection Warrior',
    root: false,
  },
  {
    id: 'combat-mechanics',
    text: 'Combat Mechanics',
    root: true,
  },
  {
    id: 'combat-mechanics.battle-resurrection',
    text: 'Battle Resurrection',
    root: false,
  },
  {
    id: 'combat-mechanics.consumables',
    text: 'Consumables',
    root: false,
  },
  {
    id: 'combat-mechanics.group-buffs',
    text: 'Group Buffs',
    root: false,
  },
  {
    id: 'combat-mechanics.interrupts',
    text: 'Interrupts',
    root: false,
  },
  {
    id: 'combat-mechanics.theorycrafting',
    text: 'Theorycrafting',
    root: false,
  },
  { id: 'dungeon.bfa', text: 'Dungeons', root: true },
  {
    id: 'dungeon.bfa.atal-dazar',
    text: "Atal'Dazar",
    root: false,
  },
  {
    id: 'dungeon.bfa.freehold',
    text: 'Freehold',
    root: false,
  },
  {
    id: 'dungeon.bfa.kings-rest',
    text: "Kings' Rest",
    root: false,
  },
  {
    id: 'dungeon.bfa.mechagon-junkyard',
    text: 'Mechagon Junkyard',
    root: false,
  },
  {
    id: 'dungeon.bfa.mechagon-workshop',
    text: 'Mechagon Workshop',
    root: false,
  },
  {
    id: 'dungeon.bfa.operation-mechagon',
    text: 'Operation Mechagon',
    root: false,
  },
  {
    id: 'dungeon.bfa.shrine-of-the-storm',
    text: 'Shrine of the Storm',
    root: false,
  },
  {
    id: 'dungeon.bfa.siege-of-boralus',
    text: 'Siege of Boralus',
    root: false,
  },
  {
    id: 'dungeon.bfa.temple-of-sethraliss',
    text: 'Temple of Sethraliss',
    root: false,
  },
  {
    id: 'dungeon.bfa.the-motherlode',
    text: 'The MOTHERLODE!!',
    root: false,
  },
  {
    id: 'dungeon.bfa.the-underrot',
    text: 'The Underrot',
    root: false,
  },
  {
    id: 'dungeon.bfa.tol-dagor',
    text: 'Tol Dagor',
    root: false,
  },
  {
    id: 'dungeon.bfa.waycrest-manor',
    text: 'Waycrest Manor',
    root: false,
  },
  {
    id: 'dungeon.classic',
    text: 'Classic Dungeons',
    root: true,
  },
  {
    id: 'dungeon.classic.blackfathom-deeps',
    text: 'Blackfathom Deeps',
    root: false,
  },
  {
    id: 'dungeon.classic.blackrock-depths',
    text: 'Blackrock Depths',
    root: false,
  },
  {
    id: 'dungeon.classic.blackrock-spire',
    text: 'Blackrock Spire',
    root: false,
  },
  {
    id: 'dungeon.classic.dire-maul',
    text: 'Dire Maul',
    root: false,
  },
  {
    id: 'dungeon.classic.gnomeregan',
    text: 'Gnomeregan',
    root: false,
  },
  {
    id: 'dungeon.classic.mauradon',
    text: 'Maraudon',
    root: false,
  },
  {
    id: 'dungeon.classic.ragefire-chasm',
    text: 'Ragefire Chasm',
    root: false,
  },
  {
    id: 'dungeon.classic.razorfen-downs',
    text: 'Razorfen Downs',
    root: false,
  },
  {
    id: 'dungeon.classic.razorfen-kraul',
    text: 'Razorfen Kraul',
    root: false,
  },
  {
    id: 'dungeon.classic.scholomance',
    text: 'Scholomance',
    root: false,
  },
  {
    id: 'dungeon.classic.shadowfang-keep',
    text: 'Shadowfang Keep',
    root: false,
  },
  {
    id: 'dungeon.classic.stratholme',
    text: 'Stratholme',
    root: false,
  },
  {
    id: 'dungeon.classic.temple-of-atal-hakkar',
    text: "Temple of Atal'Hakkar",
    root: false,
  },
  {
    id: 'dungeon.classic.the-deadmines',
    text: 'The Deadmines',
    root: false,
  },
  {
    id: 'dungeon.classic.the-scarlet-monastery',
    text: 'The Scarlet Monastery',
    root: false,
  },
  {
    id: 'dungeon.classic.the-stockade',
    text: 'The Stockade',
    root: false,
  },
  {
    id: 'dungeon.classic.uldaman',
    text: 'Uldaman',
    root: false,
  },
  {
    id: 'dungeon.classic.wailing-caverns',
    text: 'Wailing Caverns',
    root: false,
  },
  {
    id: 'dungeon.classic.zul-ferrak',
    text: "Zul'Farrak",
    root: false,
  },
  {
    id: 'dungeon.legion',
    text: 'Legion Dungeons',
    root: true,
  },
  {
    id: 'dungeon.legion.arcway',
    text: 'The Arcway',
    root: false,
  },
  {
    id: 'dungeon.legion.assault-on-violet-hold',
    text: 'Assault on Violet Hold',
    root: false,
  },
  {
    id: 'dungeon.legion.blackrook-hold',
    text: 'Black Rook Hold',
    root: false,
  },
  {
    id: 'dungeon.legion.cathedral-of-eternal-night',
    text: 'Cathedral of Eternal Night',
    root: false,
  },
  {
    id: 'dungeon.legion.court-of-stars',
    text: 'Court of Stars',
    root: false,
  },
  {
    id: 'dungeon.legion.darkheart-thicket',
    text: 'Darkheart Thicket',
    root: false,
  },
  {
    id: 'dungeon.legion.eye-of-azshara',
    text: 'Eye of Azshara',
    root: false,
  },
  {
    id: 'dungeon.legion.halls-of-valor',
    text: 'Halls of Valor',
    root: false,
  },
  {
    id: 'dungeon.legion.maw-of-souls',
    text: 'Maw of Souls',
    root: false,
  },
  {
    id: 'dungeon.legion.neltharions-lair',
    text: "Neltharion's Lair",
    root: false,
  },
  {
    id: 'dungeon.legion.return-to-karazhan',
    text: 'Return to Karazhan',
    root: false,
  },
  {
    id: 'dungeon.legion.seat-of-the-triumvirate',
    text: 'The Seat of the Triumvirate',
    root: false,
  },
  {
    id: 'dungeon.legion.vault-of-the-wardens',
    text: 'Vault of the Wardens',
    root: false,
  },
  {
    id: 'dungeon.shadowlands',
    text: 'Shadowlands Dungeons',
    root: true,
  },
  {
    id: 'dungeon.shadowlands.de-other-side',
    text: 'De Other Side',
    root: false,
  },
  {
    id: 'dungeon.shadowlands.halls-of-atonement',
    text: 'Halls Of Attonement',
    root: false,
  },
  {
    id: 'dungeon.shadowlands.halls-of-attonement',
    text: 'Halls Of Attonement',
    root: false,
  },
  {
    id: 'dungeon.shadowlands.mists-of-tirna-scithe',
    text: 'Mists Of Tirna Scithe',
    root: false,
  },
  {
    id: 'dungeon.shadowlands.plaguefall',
    text: 'Plaguefall',
    root: false,
  },
  {
    id: 'dungeon.shadowlands.sanguine-depths',
    text: 'Sanguine Depths',
    root: false,
  },
  {
    id: 'dungeon.shadowlands.spires-of-ascension',
    text: 'Spires Of Ascension',
    root: false,
  },
  {
    id: 'dungeon.shadowlands.the-necrotic-wake',
    text: 'The Necrotic Wake',
    root: false,
  },
  {
    id: 'dungeon.shadowlands.theater-of-pain',
    text: 'Theater Of Pain',
    root: false,
  },
  { id: 'equipment', text: 'Equipment', root: true },
  {
    id: 'equipment.azerite-traits',
    text: 'Azerite Traits',
    root: false,
  },
  {
    id: 'equipment.item-enhancements',
    text: 'Item Enhancements',
    root: false,
  },
  {
    id: 'equipment.legendaries',
    text: 'Legendaries',
    root: false,
  },
  {
    id: 'equipment.trinkets',
    text: 'Trinkets',
    root: false,
  },
  {
    id: 'general.achievements',
    text: 'Achievements',
    root: false,
  },
  {
    id: 'general.collectibles',
    text: 'Collectibles',
    root: false,
  },
  { id: 'general.covenants', text: 'Covenants', root: false },
  {
    id: 'general.currency',
    text: 'Currency',
    root: false,
  },
  {
    id: 'general.island-expeditions',
    text: 'Island Expeditions',
    root: false,
  },
  {
    id: 'general.non-combat',
    text: 'Non-Combat',
    root: false,
  },
  {
    id: 'general.pet-battles',
    text: 'Pet Battles',
    root: false,
  },
  { id: 'general.questing', text: 'Questing', root: false },
  {
    id: 'general.reputation',
    text: 'Reputation',
    root: false,
  },
  {
    id: 'general.world-events',
    text: 'World Events',
    root: false,
  },
  {
    id: 'general.world-events.brawlers-guild',
    text: "Brawler's Guild",
    root: false,
  },
  {
    id: 'general.world-events.darkmoon-faire',
    text: 'Darkmoon Faire',
    root: false,
  },
  {
    id: 'general.world-events.holidays',
    text: 'Holidays',
    root: false,
  },
  { id: 'mdtspeed', text: 'Speed', root: true },
  {
    id: 'mdtspeed.easy-going',
    text: 'Easy Going',
    root: false,
  },
  {
    id: 'mdtspeed.gotta-go-fast',
    text: 'Gotta Go Fast',
    root: false,
  },
  {
    id: 'mdtspeed.racing-number-one',
    text: 'Racing for #1',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s1.w1',
    text: 'S1 Week 1',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s1.w10',
    text: 'S1 Week 10',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s1.w11',
    text: 'S1 Week 11',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s1.w12',
    text: 'S1 Week 12',
    root: false,
  },
  { id: 'mdtweek.bfa.s1.w2', text: 'S1 Week 2', root: false },
  {
    id: 'mdtweek.bfa.s1.w3',
    text: 'S1 Week 3',
    root: false,
  },
  { id: 'mdtweek.bfa.s1.w4', text: 'S1 Week 4', root: false },
  {
    id: 'mdtweek.bfa.s1.w5',
    text: 'S1 Week 5',
    root: false,
  },
  { id: 'mdtweek.bfa.s1.w6', text: 'S1 Week 6', root: false },
  {
    id: 'mdtweek.bfa.s1.w7',
    text: 'S1 Week 7',
    root: false,
  },
  { id: 'mdtweek.bfa.s1.w8', text: 'S1 Week 8', root: false },
  {
    id: 'mdtweek.bfa.s1.w9',
    text: 'S1 Week 9',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s2.w1',
    text: 'S2 Week 1',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s2.w10',
    text: 'S2 Week 10',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s2.w11',
    text: 'S2 Week 11',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s2.w12',
    text: 'S2 Week 12',
    root: false,
  },
  { id: 'mdtweek.bfa.s2.w2', text: 'S2 Week 2', root: false },
  {
    id: 'mdtweek.bfa.s2.w3',
    text: 'S2 Week 3',
    root: false,
  },
  { id: 'mdtweek.bfa.s2.w4', text: 'S2 Week 4', root: false },
  {
    id: 'mdtweek.bfa.s2.w5',
    text: 'S2 Week 5',
    root: false,
  },
  { id: 'mdtweek.bfa.s2.w6', text: 'S2 Week 6', root: false },
  {
    id: 'mdtweek.bfa.s2.w7',
    text: 'S2 Week 7',
    root: false,
  },
  { id: 'mdtweek.bfa.s2.w8', text: 'S2 Week 8', root: false },
  {
    id: 'mdtweek.bfa.s2.w9',
    text: 'S2 Week 9',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s3.w1',
    text: 'S3 Week 1',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s3.w10',
    text: 'S3 Week 10',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s3.w11',
    text: 'S3 Week 11',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s3.w12',
    text: 'S3 Week 12',
    root: false,
  },
  { id: 'mdtweek.bfa.s3.w2', text: 'S3 Week 2', root: false },
  {
    id: 'mdtweek.bfa.s3.w3',
    text: 'S3 Week 3',
    root: false,
  },
  { id: 'mdtweek.bfa.s3.w4', text: 'S3 Week 4', root: false },
  {
    id: 'mdtweek.bfa.s3.w5',
    text: 'S3 Week 5',
    root: false,
  },
  { id: 'mdtweek.bfa.s3.w6', text: 'S3 Week 6', root: false },
  {
    id: 'mdtweek.bfa.s3.w7',
    text: 'S3 Week 7',
    root: false,
  },
  { id: 'mdtweek.bfa.s3.w8', text: 'S3 Week 8', root: false },
  {
    id: 'mdtweek.bfa.s3.w9',
    text: 'S3 Week 9',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s4.w1',
    text: 'S4 Week 1',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s4.w10',
    text: 'S4 Week 10',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s4.w11',
    text: 'S4 Week 11',
    root: false,
  },
  {
    id: 'mdtweek.bfa.s4.w12',
    text: 'S4 Week 12',
    root: false,
  },
  { id: 'mdtweek.bfa.s4.w2', text: 'S4 Week 2', root: false },
  {
    id: 'mdtweek.bfa.s4.w3',
    text: 'S4 Week 3',
    root: false,
  },
  { id: 'mdtweek.bfa.s4.w4', text: 'S4 Week 4', root: false },
  {
    id: 'mdtweek.bfa.s4.w5',
    text: 'S4 Week 5',
    root: false,
  },
  { id: 'mdtweek.bfa.s4.w6', text: 'S4 Week 6', root: false },
  {
    id: 'mdtweek.bfa.s4.w7',
    text: 'S4 Week 7',
    root: false,
  },
  { id: 'mdtweek.bfa.s4.w8', text: 'S4 Week 8', root: false },
  {
    id: 'mdtweek.bfa.s4.w9',
    text: 'S4 Week 9',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w1',
    text: 'S1 Week 1',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w10',
    text: 'S1 Week 10',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w11',
    text: 'S1 Week 11',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w12',
    text: 'S1 Week 12',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w2',
    text: 'S1 Week 2',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w3',
    text: 'S1 Week 3',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w4',
    text: 'S1 Week 4',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w5',
    text: 'S1 Week 5',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w6',
    text: 'S1 Week 6',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w7',
    text: 'S1 Week 7',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w8',
    text: 'S1 Week 8',
    root: false,
  },
  {
    id: 'mdtweek.shadowlands.s1.w9',
    text: 'S1 Week 9',
    root: false,
  },
  {
    id: 'plater.plater-animations',
    text: 'Plater Animations',
    root: false,
  },
  {
    id: 'plater.plater-mods',
    text: 'Plater Mods',
    root: false,
  },
  {
    id: 'plater.plater-npc-colors',
    text: 'Plater NPC Colors',
    root: false,
  },
  {
    id: 'plater.plater-profiles',
    text: 'Plater Profiles',
    root: false,
  },
  {
    id: 'plater.plater-scripts',
    text: 'Plater Scripts',
    root: false,
  },
  {
    id: 'professions.crafting',
    text: 'Crafting Professions',
    root: true,
  },
  {
    id: 'professions.crafting.alchemy',
    text: 'Alchemy',
    root: false,
  },
  {
    id: 'professions.crafting.blacksmithing',
    text: 'Blacksmithing',
    root: false,
  },
  {
    id: 'professions.crafting.enchanting',
    text: 'Enchanting',
    root: false,
  },
  {
    id: 'professions.crafting.engineering',
    text: 'Engineering',
    root: false,
  },
  {
    id: 'professions.crafting.inscription',
    text: 'Inscription',
    root: false,
  },
  {
    id: 'professions.crafting.jewelcrafting',
    text: 'Jewelcrafting',
    root: false,
  },
  {
    id: 'professions.crafting.leatherworking',
    text: 'Leatherworking',
    root: false,
  },
  {
    id: 'professions.crafting.tailoring',
    text: 'Tailoring',
    root: false,
  },
  {
    id: 'professions.gathering',
    text: 'Gathering Professions',
    root: true,
  },
  {
    id: 'professions.gathering.herbalism',
    text: 'Herbalism',
    root: false,
  },
  {
    id: 'professions.gathering.mining',
    text: 'Mining',
    root: false,
  },
  {
    id: 'professions.gathering.skinning',
    text: 'Skinning',
    root: false,
  },
  {
    id: 'professions.secondary',
    text: 'Secondary Professions',
    root: true,
  },
  {
    id: 'professions.secondary.archeology',
    text: 'Archaeology',
    root: false,
  },
  {
    id: 'professions.secondary.cooking',
    text: 'Cooking',
    root: false,
  },
  {
    id: 'professions.secondary.first-aid',
    text: 'First Aid',
    root: false,
  },
  {
    id: 'professions.secondary.fishing',
    text: 'Fishing',
    root: false,
  },
  { id: 'pve.torghast', text: 'Torghast, Tower of the Damned', root: true },
  {
    id: 'pvp',
    text: 'PvP',
    root: true,
  },
  { id: 'pvp.arena', text: 'Arena', root: false },
  {
    id: 'pvp.battlegrounds',
    text: 'Battlegrounds',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne',
    text: 'Antorus the Burning Throne',
    root: true,
  },
  {
    id: 'raid.antorus-the-burning-throne.aggramar',
    text: 'Aggramar',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.antoran-high-command',
    text: 'Antoran High Command',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.argus-the-unmaker',
    text: 'Argus the Unmaker',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.eonar-the-lifebender',
    text: 'Eonar the Lifebender',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.garothi-worldbreaker',
    text: 'Garothi Worldbreaker',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.hounds-of-sargeras',
    text: 'Felhouds of Sargeras',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.imonar-the-soulhunter',
    text: 'Imonar the Soulhunter',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.kingaroth',
    text: "Kin'garoth",
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.portal-keeper-hasabel',
    text: 'Portal Keeper Hasabel',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.the-coven-of-shivarra',
    text: 'The Coven of Shivarra',
    root: false,
  },
  {
    id: 'raid.antorus-the-burning-throne.varimathras',
    text: 'Varimathras',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar',
    text: "Battle of Dazar'alor",
    root: true,
  },
  {
    id: 'raid.battle-of-zuldazar.conclave-of-the-chosen',
    text: 'Conclave of the Chosen',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.flamefist-and-the-illuminated',
    text: 'Flamefist and the Illuminated',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.frida-ironbellows',
    text: 'Frida Ironbellows',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.grimfang-and-firecaller',
    text: 'Grimfang and Firecaller',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.grong-the-jungle-lord',
    text: 'Grong the Jungle Lord',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.grong-the-revenant',
    text: 'Grong the Revanant',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.high-tinker-mekkatorque',
    text: 'High Tinker Mekkatorque',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.jaina-proudmoore',
    text: 'Lady Jaina Proudmoore',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.king-rastakhan',
    text: 'King Rastakhan',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.opulence',
    text: 'Opulence',
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.ra-wani-kanae',
    text: "Ra'wani Kanae",
    root: false,
  },
  {
    id: 'raid.battle-of-zuldazar.stormwall-blockade',
    text: 'Stormwall Blockade',
    root: false,
  },
  {
    id: 'raid.blackwing-lair',
    text: 'Blackwing Lair',
    root: true,
  },
  {
    id: 'raid.blackwing-lair.broodlord-lashlayer',
    text: 'Broodlord Lashlayer',
    root: false,
  },
  {
    id: 'raid.blackwing-lair.chromaggus',
    text: 'Chromaggus',
    root: false,
  },
  {
    id: 'raid.blackwing-lair.ebonroc',
    text: 'Ebonroc',
    root: false,
  },
  {
    id: 'raid.blackwing-lair.firemaw',
    text: 'Firemaw',
    root: false,
  },
  {
    id: 'raid.blackwing-lair.flamegor',
    text: 'Flamegor',
    root: false,
  },
  {
    id: 'raid.blackwing-lair.nefarian',
    text: 'Nefarian',
    root: false,
  },
  {
    id: 'raid.blackwing-lair.razorgore-the-untamed',
    text: 'Razorgore the Untamed',
    root: false,
  },
  {
    id: 'raid.blackwing-lair.vaelastrasz-the-corrupt',
    text: 'Vaelastrasz the Corrupt',
    root: false,
  },
  {
    id: 'raid.crucible-of-storms',
    text: 'Crucible of Storms',
    root: true,
  },
  {
    id: 'raid.crucible-of-storms.the-restless-cabal',
    text: 'Zaxasj the Speaker',
    root: false,
  },
  {
    id: 'raid.crucible-of-storms.uunat-harbinger-of-the-void',
    text: "Uu'nat Harbinger of the Void",
    root: false,
  },
  {
    id: 'raid.emerald-nightmare',
    text: 'The Emerald Nightmare',
    root: false,
  },
  {
    id: 'raid.emerald-nightmare.cenarius',
    text: 'Cenarius',
    root: false,
  },
  {
    id: 'raid.emerald-nightmare.dragons-of-nightmare',
    text: 'Dragons of Nightmare',
    root: false,
  },
  {
    id: 'raid.emerald-nightmare.elerethe-renferal',
    text: 'Elerethe Renferal',
    root: false,
  },
  {
    id: 'raid.emerald-nightmare.ilgynoth',
    text: "Il'gynoth The Heart of Corruption",
    root: false,
  },
  {
    id: 'raid.emerald-nightmare.nythendra',
    text: 'Nythendra',
    root: false,
  },
  {
    id: 'raid.emerald-nightmare.ursoc',
    text: 'Ursoc',
    root: false,
  },
  {
    id: 'raid.emerald-nightmare.xavius',
    text: 'Xavius',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel',
    text: 'Hellfire Citadel',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.archimonde',
    text: 'Archimonde',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.assault',
    text: 'Hellfire Assault',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.fel-lord-zakuun',
    text: 'Fel Lord Zakuun',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.gorefiend',
    text: 'Gorefiend',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.high-council',
    text: 'Hellfire High Council',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.iron-reaver',
    text: 'Iron Reaver',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.kilrogg-deadeye',
    text: 'Kilrogg Deadeye',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.kormrok',
    text: 'Kormrok',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.mannoroth',
    text: 'Mannoroth',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.shadow-lord-iskar',
    text: 'Shadow-Lord Iskar',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.socrethar-the-eternal',
    text: 'Socrethar the Eternal',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.tyrant-velhari',
    text: 'Tyrant Velhari',
    root: false,
  },
  {
    id: 'raid.hellfire-citadel.xhulhorac',
    text: "Xhul'horac",
    root: false,
  },
  {
    id: 'raid.molten-core',
    text: 'Molten Core',
    root: true,
  },
  {
    id: 'raid.molten-core.baron-geddon',
    text: 'Baron Geddon',
    root: false,
  },
  {
    id: 'raid.molten-core.garr',
    text: 'Garr',
    root: false,
  },
  {
    id: 'raid.molten-core.gehennas',
    text: 'Gehennas',
    root: false,
  },
  {
    id: 'raid.molten-core.golemagg-the-incinerator',
    text: 'Golemagg The Incinerator',
    root: false,
  },
  {
    id: 'raid.molten-core.lucifron',
    text: 'Lucifron',
    root: false,
  },
  {
    id: 'raid.molten-core.magmadar',
    text: 'Magmadar',
    root: false,
  },
  {
    id: 'raid.molten-core.majordomo-executus',
    text: 'Majordomo Executus',
    root: false,
  },
  {
    id: 'raid.molten-core.ragnaros',
    text: 'Ragnaros',
    root: false,
  },
  {
    id: 'raid.molten-core.shazzrah',
    text: 'Shazzrah',
    root: false,
  },
  {
    id: 'raid.molten-core.sulfuron-harbinger',
    text: 'Sulfuron Harbinger',
    root: false,
  },
  {
    id: 'raid.nathria',
    text: 'Castle Nathria',
    root: true,
  },
  {
    id: 'raid.nathria.altimor-the-huntsman',
    text: 'Altimor the Huntsman',
    root: false,
  },
  {
    id: 'raid.nathria.artificer-xymox',
    text: "Artificer Xy'Mox",
    root: false,
  },
  {
    id: 'raid.nathria.hungering-destroyer',
    text: 'Hungering Destroyer',
    root: false,
  },
  {
    id: 'raid.nathria.kaelthas-sunstrider',
    text: "Sun King's Salvation",
    root: false,
  },
  {
    id: 'raid.nathria.lady-inerva-darkvein',
    text: 'Lady Inerva Darkvein',
    root: false,
  },
  {
    id: 'raid.nathria.shriekwing',
    text: 'Shriekwing',
    root: false,
  },
  {
    id: 'raid.nathria.sire-denathrius',
    text: 'Sire Denathrius',
    root: false,
  },
  {
    id: 'raid.nathria.sludgefist',
    text: 'Sludgefist',
    root: false,
  },
  {
    id: 'raid.nathria.stone-legion-generals',
    text: 'Stone Legion Generals',
    root: false,
  },
  {
    id: 'raid.nathria.the-council-of-blood',
    text: 'The Council Of Blood',
    root: false,
  },
  {
    id: 'raid.naxxramas',
    text: 'Naxxramas',
    root: true,
  },
  {
    id: 'raid.naxxramas.anub-rekhan',
    text: "Anuh'Rekhan",
    root: false,
  },
  {
    id: 'raid.naxxramas.gluth',
    text: 'Gluth',
    root: false,
  },
  {
    id: 'raid.naxxramas.gothik-the-harvester',
    text: 'Gothik the Harvester',
    root: false,
  },
  {
    id: 'raid.naxxramas.grand-widow-faerlina',
    text: 'Grand Widow Faerlina',
    root: false,
  },
  {
    id: 'raid.naxxramas.grobbulus',
    text: 'Grobbulus',
    root: false,
  },
  {
    id: 'raid.naxxramas.heigan-the-unclean',
    text: 'Heigan the Unclean',
    root: false,
  },
  {
    id: 'raid.naxxramas.instructor-razuvious',
    text: 'Instructor Razuvious',
    root: false,
  },
  {
    id: 'raid.naxxramas.kel-thuzad',
    text: "Kel'Thuzad",
    root: false,
  },
  {
    id: 'raid.naxxramas.loatheb',
    text: 'Loatheb',
    root: false,
  },
  {
    id: 'raid.naxxramas.maexxna',
    text: 'Maexxna',
    root: false,
  },
  {
    id: 'raid.naxxramas.noth-the-plaguebringer',
    text: 'Noth the Plaguebringer',
    root: false,
  },
  {
    id: 'raid.naxxramas.patchwerk',
    text: 'Patchwerk',
    root: false,
  },
  {
    id: 'raid.naxxramas.sapphiron',
    text: 'Sapphiron',
    root: false,
  },
  {
    id: 'raid.naxxramas.thaddius',
    text: 'Thaddius',
    root: false,
  },
  {
    id: 'raid.naxxramas.the-four-horsemen',
    text: 'The Four Horsemen',
    root: false,
  },
  {
    id: 'raid.nighthold',
    text: 'The Nighthold',
    root: false,
  },
  {
    id: 'raid.nighthold.chronomatic-anomaly',
    text: 'Chronomatic Anomaly',
    root: false,
  },
  {
    id: 'raid.nighthold.grand-magistrix-elisande',
    text: 'Grand Magistrix Elisande',
    root: false,
  },
  {
    id: 'raid.nighthold.guldan',
    text: "Gul'dan",
    root: false,
  },
  {
    id: 'raid.nighthold.high-botanist-telarn',
    text: "High Botanist Tel'arn",
    root: false,
  },
  {
    id: 'raid.nighthold.krosus',
    text: 'Krosus',
    root: false,
  },
  {
    id: 'raid.nighthold.skorpyron',
    text: 'Skorpyron',
    root: false,
  },
  {
    id: 'raid.nighthold.spellblade-aluriel',
    text: 'Spellblade Aluriel',
    root: false,
  },
  {
    id: 'raid.nighthold.star-augur-etraeus',
    text: 'Star Augur Etraeus',
    root: false,
  },
  {
    id: 'raid.nighthold.tichondrius',
    text: 'Tichondrius',
    root: false,
  },
  {
    id: 'raid.nighthold.trilliax',
    text: 'Trilliax',
    root: false,
  },
  {
    id: 'raid.nyalotha',
    text: "Ny'alotha",
    root: true,
  },
  {
    id: 'raid.nyalotha.carapace-of-nzoth',
    text: "Carapace of N'Zoth",
    root: false,
  },
  {
    id: 'raid.nyalotha.dark-inquisitor-xanesh',
    text: 'Dark Inquisitor Xanesh',
    root: false,
  },
  {
    id: 'raid.nyalotha.drestagath',
    text: "Drest'agath",
    root: false,
  },
  {
    id: 'raid.nyalotha.hivemind',
    text: 'The Hivemind',
    root: false,
  },
  {
    id: 'raid.nyalotha.ilgynoth-corruption-reborn',
    text: "Il'gynoth Corruption Reborn",
    root: false,
  },
  {
    id: 'raid.nyalotha.maut',
    text: 'Maut',
    root: false,
  },
  {
    id: 'raid.nyalotha.nzoth-the-corruptor',
    text: "N'Zoth the Corruptor",
    root: false,
  },
  {
    id: 'raid.nyalotha.ra-den-the-despoiled',
    text: 'Ra-den the Despoiled',
    root: false,
  },
  {
    id: 'raid.nyalotha.shadhar-the-insatiable',
    text: "Shad'har the Insatiable",
    root: false,
  },
  {
    id: 'raid.nyalotha.the-prophet-skitra',
    text: 'The Prophet Skitra',
    root: false,
  },
  {
    id: 'raid.nyalotha.vexiona',
    text: 'Vexiona',
    root: false,
  },
  {
    id: 'raid.nyalotha.wrathion-the-black-emperor',
    text: 'Wrathion the Black Emperor',
    root: false,
  },
  {
    id: 'raid.ruins-of-ahn-qiraj',
    text: "Ruins of Ahn'Qiraj",
    root: true,
  },
  {
    id: 'raid.ruins-of-ahn-qiraj.ayamiss-the-hunter',
    text: 'Ayamiss the Hunter',
    root: false,
  },
  {
    id: 'raid.ruins-of-ahn-qiraj.buru-the-gorger',
    text: 'Buru the Gorger',
    root: false,
  },
  {
    id: 'raid.ruins-of-ahn-qiraj.general-rajaxx',
    text: 'General Rajaxx',
    root: false,
  },
  {
    id: 'raid.ruins-of-ahn-qiraj.kurinaxx',
    text: 'Kurinaxx',
    root: false,
  },
  {
    id: 'raid.ruins-of-ahn-qiraj.moam',
    text: 'Moam',
    root: false,
  },
  {
    id: 'raid.ruins-of-ahn-qiraj.ossirian-the-unscarred',
    text: 'Ossirian the Unscarred',
    root: false,
  },
  {
    id: 'raid.single-raid.azuregos',
    text: 'Azuregos',
    root: false,
  },
  {
    id: 'raid.single-raid.emeriss',
    text: 'Emeriss',
    root: false,
  },
  {
    id: 'raid.single-raid.kazzak',
    text: 'Lord Kazzak',
    root: false,
  },
  {
    id: 'raid.single-raid.lethon',
    text: 'Lethon',
    root: false,
  },
  {
    id: 'raid.single-raid.onyxia',
    text: 'Onyxia',
    root: false,
  },
  {
    id: 'raid.single-raid.taerar',
    text: 'Taerar',
    root: false,
  },
  {
    id: 'raid.single-raid.ysondre',
    text: 'Ysondre',
    root: false,
  },
  {
    id: 'raid.temple-of-ahn-qiraj',
    text: "Temple of Ahn'Qiraj",
    root: true,
  },
  {
    id: 'raid.temple-of-ahn-qiraj.battleguard-sartura',
    text: 'Battleguard Satura',
    root: false,
  },
  {
    id: 'raid.temple-of-ahn-qiraj.bug-trio',
    text: 'Bug Trio',
    root: false,
  },
  {
    id: 'raid.temple-of-ahn-qiraj.cthun',
    text: "C'thun",
    root: false,
  },
  {
    id: 'raid.temple-of-ahn-qiraj.fankriss-the-undying',
    text: 'Fankriss the Undying',
    root: false,
  },
  {
    id: 'raid.temple-of-ahn-qiraj.ouro',
    text: 'Ouro',
    root: false,
  },
  {
    id: 'raid.temple-of-ahn-qiraj.princess-huhuran',
    text: 'Princess Huhuran',
    root: false,
  },
  {
    id: 'raid.temple-of-ahn-qiraj.the-prophet-skeram',
    text: 'The Prophet Skeram',
    root: false,
  },
  {
    id: 'raid.temple-of-ahn-qiraj.twin-emperors',
    text: 'Twin Emperors',
    root: false,
  },
  {
    id: 'raid.temple-of-ahn-qiraj.viscidus',
    text: 'Viscidus',
    root: false,
  },
  {
    id: 'raid.the-eternal-palace',
    text: 'The Eternal Palace',
    root: true,
  },
  {
    id: 'raid.the-eternal-palace.abyssal-commander-sivara',
    text: 'Abyssal Commander Sivara',
    root: false,
  },
  {
    id: 'raid.the-eternal-palace.herald-of-nzoth',
    text: "Za'qul Herald of N'zoth",
    root: false,
  },
  {
    id: 'raid.the-eternal-palace.lady-priscilla-ashvane',
    text: 'Lady Priscilla Ashvane',
    root: false,
  },
  {
    id: 'raid.the-eternal-palace.queen-azshara',
    text: 'Queen Azshara',
    root: false,
  },
  {
    id: 'raid.the-eternal-palace.rage-of-azshara',
    text: 'Rage of Azshara',
    root: false,
  },
  {
    id: 'raid.the-eternal-palace.the-hatchery',
    text: 'The Hatchery',
    root: false,
  },
  {
    id: 'raid.the-eternal-palace.the-queens-court',
    text: "The Queen's Court",
    root: false,
  },
  {
    id: 'raid.the-eternal-palace.underwater-monstrosity',
    text: 'Blackwater Behemoth',
    root: false,
  },
  {
    id: 'raid.tomb-of-sargeras',
    text: 'Tomb of Sargeras',
    root: true,
  },
  {
    id: 'raid.tomb-of-sargeras.demonic-inquisition',
    text: 'Demonic Inquisition',
    root: false,
  },
  {
    id: 'raid.tomb-of-sargeras.fallen-avatar',
    text: 'Fallen Avatar',
    root: false,
  },
  {
    id: 'raid.tomb-of-sargeras.goroth',
    text: 'Goroth',
    root: false,
  },
  {
    id: 'raid.tomb-of-sargeras.harjatan-the-bludger',
    text: 'Harjatan',
    root: false,
  },
  {
    id: 'raid.tomb-of-sargeras.kiljaeden',
    text: "Kil'jaeden",
    root: false,
  },
  {
    id: 'raid.tomb-of-sargeras.maiden-of-vigilance',
    text: 'Maiden of Vigilance',
    root: false,
  },
  {
    id: 'raid.tomb-of-sargeras.mistress-sasszine',
    text: "Mistress Sassz'ine",
    root: false,
  },
  {
    id: 'raid.tomb-of-sargeras.sisters-of-the-moon',
    text: 'Sisters of the Moon',
    root: false,
  },
  {
    id: 'raid.tomb-of-sargeras.the-desolate-host',
    text: 'The Desolate Host',
    root: false,
  },
  {
    id: 'raid.trial-of-valor',
    text: 'Trial of Valor',
    root: false,
  },
  {
    id: 'raid.trial-of-valor.guarm',
    text: 'Guarm',
    root: false,
  },
  {
    id: 'raid.trial-of-valor.helya',
    text: 'Odyn',
    root: false,
  },
  { id: 'raid.trial-of-valor.odyn', text: 'Odyn', root: false },
  {
    id: 'raid.uldir',
    text: 'Uldir',
    root: true,
  },
  {
    id: 'raid.uldir.fetid-devourer',
    text: 'Fetid Devourer',
    root: false,
  },
  { id: 'raid.uldir.ghuun', text: "G'huun", root: false },
  {
    id: 'raid.uldir.mother',
    text: 'MOTHER',
    root: false,
  },
  {
    id: 'raid.uldir.mythrax-the-unraveler',
    text: 'Mythrax the Unraveler',
    root: false,
  },
  {
    id: 'raid.uldir.taloc-the-corrupted',
    text: 'Taloc the Corrupted',
    root: false,
  },
  {
    id: 'raid.uldir.vectis',
    text: 'Vectis',
    root: false,
  },
  {
    id: 'raid.uldir.zekvoz-herald-of-nzoth',
    text: "Zek'voz Herald of N'zoth",
    root: false,
  },
  {
    id: 'raid.uldir.zul-reborn',
    text: 'Zul Reborn',
    root: false,
  },
  {
    id: 'raid.zul-gurub',
    text: "Zul'Gurub",
    root: true,
  },
  {
    id: 'raid.zul-gurub.bloodlord-mandokir',
    text: 'Bloodlord Mandokir',
    root: false,
  },
  {
    id: 'raid.zul-gurub.edge-of-madness',
    text: 'Edge of Madness',
    root: false,
  },
  {
    id: 'raid.zul-gurub.gahzranka',
    text: "Gahz'ranka",
    root: false,
  },
  {
    id: 'raid.zul-gurub.hakkar',
    text: 'Hakkar',
    root: false,
  },
  {
    id: 'raid.zul-gurub.high-priest-thekal',
    text: 'High Priest Thekal',
    root: false,
  },
  {
    id: 'raid.zul-gurub.high-priest-venoxis',
    text: 'High Priest Venoxis',
    root: false,
  },
  {
    id: 'raid.zul-gurub.high-priestess-arlokk',
    text: 'High Priestess Arlokk',
    root: false,
  },
  {
    id: 'raid.zul-gurub.high-priestess-jeklik',
    text: 'High Priestess Jeklik',
    root: false,
  },
  {
    id: 'raid.zul-gurub.high-priestess-mar-li',
    text: "High Priestess Mar'li",
    root: false,
  },
  {
    id: 'raid.zul-gurub.jindo-the-hexer',
    text: "Jin'do the Hexer",
    root: false,
  },
  {
    id: 'totalrp.campaigns',
    text: 'Campaigns',
    root: true,
  },
  {
    id: 'totalrp.campaigns.alliance-campaigns',
    text: 'Alliance Campaigns',
    root: false,
  },
  {
    id: 'totalrp.campaigns.horde-campaigns',
    text: 'Horde Campaigns',
    root: false,
  },
  { id: 'totalrp.english', text: 'English', root: true },
  {
    id: 'totalrp.french',
    text: 'French',
    root: true,
  },
  { id: 'totalrp.german', text: 'German', root: true },
  {
    id: 'totalrp.items.containers',
    text: 'Containers',
    root: false,
  },
  {
    id: 'totalrp.items.documents',
    text: 'Documents',
    root: false,
  },
  {
    id: 'totalrp.items.equipment',
    text: 'Equipment',
    root: false,
  },
  {
    id: 'totalrp.items.expert-mode',
    text: 'Expert Mode',
    root: false,
  },
  {
    id: 'totalrp.items.miscellaneous',
    text: 'Miscellaneous',
    root: false,
  },
  {
    id: 'totalrp.items.normal-mode',
    text: 'Normal Mode',
    root: false,
  },
  { id: 'totalrp.items.toys', text: 'Toys', root: false },
  {
    id: 'totalrp.spanish',
    text: 'Spanish',
    root: true,
  },
  {
    id: 'vuhdo.vuhdo-bouquets',
    text: 'Vuhdo Bouquets',
    root: false,
  },
  {
    id: 'vuhdo.vuhdo-key-layouts',
    text: 'Vuhdo Key Layouts',
    root: false,
  },
  { id: 'vuhdo.vuhdo-profiles', text: 'Vuhdo Profiles', root: false },
]
